CREATE TABLE PEOPLE(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
SURNAME VARCHAR(20),
AGE INT,
GENDER CHAR,
CITY VARCHAR(20),
COUNTRY VARCHAR(20),
SALARY INT
);

INSERT INTO PEOPLE VALUES (200,'OGUZ','KAGAN',46,'E','BERLIN','ALMANYA',3200);
INSERT INTO PEOPLE VALUES (201,'BURAK','AK',30,'E','PARIS','FRANSA',5000);
INSERT INTO PEOPLE VALUES (202,'FUNDA','NAR',30,'K','BERLIN','ALMANYA',4200);
INSERT INTO PEOPLE VALUES (203,'MUHAMMET','BIR',40,'E','PARIS','FRANSA',3000);
INSERT INTO PEOPLE VALUES (204,'IHSAN','OZAY',30,'E','IZMIR','TURKIYE',10000);
INSERT INTO PEOPLE VALUES (205,'FATMA','YILMAZ',40,'K','ISTANBUL','TURKIYE',20000);
INSERT INTO PEOPLE VALUES (206,'RESUL','DEMIR',35,'E','ANKARA','TURKIYE',21000);
INSERT INTO PEOPLE VALUES (207,'ELIF','CAN',38,'K','ISPARTA','TURKIYE',19000);
INSERT INTO PEOPLE VALUES (208,'SINAN','BURC',32,'E','LONDON','INGILTERE',60000);
INSERT INTO PEOPLE VALUES (209,'HAMZA','KUL',29,'E','LONDON','INGILTERE',63000);
INSERT INTO PEOPLE VALUES (210,'AYLIN','VAN',51,'K','LONDON','INGILTERE',38000);

SELECT * FROM PEOPLE;

--ULKELERE GORE ORTALAMA YASI LISTELEYINIZ.
SELECT COUNTRY,ROUND(AVG(AGE)) AS AVERAGE_AGE FROM PEOPLE
GROUP BY COUNTRY;

--ULKELERE GORE KAC CALISAN OLDUGUNU LISTELEYINIZ.
SELECT COUNTRY, COUNT(NAME) AS NUMBER_WORKER FROM PEOPLE
GROUP BY COUNTRY;

--CINSIYETE GORE YAS ORTALAMASINI BULUNUZ.
SELECT GENDER,ROUND(AVG(AGE)) AS AVAREGE_AGE FROM PEOPLE
GROUP BY GENDER;


SELECT
