--PEOPLE TABLE 'INI COUNTRY VE CITY 'LERE GORE GRUPLAYARAK LISTLEYINIZ.
SELECT country,city FROM PEOPLE
GROUP BY COUNTRY, city; 

--COUNTRY VE CITY'LERE GORE WORKER SAYISINI BELIRLEYINIZ.
SELECT COUNTRY,CITY,COUNT(ID) AS NUMBER_WORKER FROM PEOPLE
GROUP BY COUNTRY, city;

--COUNTRY VE GENDER'A GORE NUMBER OF WORKER'I VE AVAREGE OF AGE'I LISTELEYINIZ.
SELECT COUNTRY,GENDER,COUNT(ID) AS NUMBER_WORKER,ROUND(AVG(AGE)) AS AVAREGE_AGE 
FROM PEOPLE
GROUP BY COUNTRY, GENDER;

--SALARY'SI 3000'DEN BUYUK OLANLARIN, COUNTRY VE GENDER'A GORE NUMBER OF WORKER'I VE AVAREGE OF AGE'I LISTELEYINIZ.
SELECT COUNTRY,GENDER,COUNT(ID) AS NUMBER_OF_WORKERS,ROUND(AVG(AGE)) AS AVAREGE_AGE
FROM PEOPLE WHERE SALARY>10000
GROUP BY COUNTRY,GENDER;

SELECT * FROM PEOPLE;

/*----------HAVING ----------------------------------------
SART BELIRTMEK ICIN KULLANILIR.
GROUP BY KOMUTUNDAN SONRA YER ALIR.
WHERE KOMUTUNDAN FARKI : GRUPLAMA YAPTIKTAN SONRA, CIKAN SONUCTA SART KOSULACAKSA HAVING KOMUTU KULLANILIR.
-----------------------------------------------------------*/

--COUNTRY'LERE GORE AGE ORTALMASINI BULUP YAS ORTALAMASI 33 DEN BUYUK OLANLARI LISTELEYINIZ.
SELECT COUNTRY,ROUND(AVG(AGE),2) AS AVAREGE_AGE FROM PEOPLE
GROUP BY COUNTRY
HAVING AVG(AGE)>33;

--COUNTRY'LERE GORE ORTALAMA SALARY'I BULUP, ORTALAMA SALARY 30 000 DEN BUYUK OLANLARI LISTELEYINIZ.
SELECT COUNTRY,ROUND(AVG(SALARY),2) AS AVAREGE_SALARY
FROM PEOPLE
GROUP BY COUNTRY
HAVING AVG(SALARY)>30000;

/*------------UNION------------------------
--IKI VEYA DAHA FAZLA SORGU IFADESININ SONUC KUMELERINI BIRLESTIREREK TEK BIR SONUC KUMESI OLUSTURUR.

UNION    --> SADECE BENZERSIZ VERILERI ALIR.
UNION ALL--> BENZER VERILERIDE ALIR.

NOT : BIRLESIK OLAN SORGU IFADESININ DATA TURU DIGER SORGULARDAKI IFADELERIN TURU ILE UYUMLU OLMALIDIR.

-------------------------------------------*/

CREATE TABLE PERSONNELS(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
CITY VARCHAR(20),
SALARY INT,
COMPANY VARCHAR(20)
);

INSERT INTO PERSONNELS VALUES (200,'OGUZ','ISTANBUL',55000,'HONDA');
INSERT INTO PERSONNELS VALUES (201,'BURAK','ISTANBUL',4500,'TOYATA');
INSERT INTO PERSONNELS VALUES (202,'FUNDA','ANKARA',3500,'HONDA');
INSERT INTO PERSONNELS VALUES (203,'MUHAMMET','ISTANBUL',3500,'HONDA');
INSERT INTO PERSONNELS VALUES (204,'IHSAN','IZMIR',6000,'FORD');
INSERT INTO PERSONNELS VALUES (205,'FATMA','ANKARA',7000,'TOFAS');
INSERT INTO PERSONNELS VALUES (206,'RESUL','ANKARA',4500,'FORD');
INSERT INTO PERSONNELS VALUES (207,'ELIF','BURSA',4200,'HONDA');

SELECT * FROM PERSONNELS;

--SALARY'SI 4000'DEN BUYUK OLAN PERSONEL ISIMLERINI VE SALARY'SI 5000' DEN COK OLAN SEHIRLERI GOSTEREN TEKRARSIZ SORGUYU YAZINIZ.
SELECT NAME AS NAME_SALARY,SALARY FROM PERSONNELS
WHERE SALARY>4000
UNION 
SELECT CITY,SALARY FROM PERSONNELS
WHERE SALARY>5000;

--NAME'I IHSAN OLAN KISILERIN ALDIGI SALARY'LERI VE CITY'LERI 'ISTANBUL' OLAN PERSONELIN
--SALARY'LERINI TEKRARSIZ BUYUKTEN KUCUGE DOGRU SIRALAYARAK BIR TABLODA GOSTEREN SORGUYU YAZINIZ.

SELECT name AS NAME_CITY,salary  from personnels
where name='IHSAN' 
UNION
SELECT CITY,SALARY FROM PERSONNELS
WHERE CITY='ISTANBUL'
ORDER BY SALARY DESC;